### ISSUE TITLE
onUploadPogress does not work as expected 

### ISSUE THREAD

**Issue by sheldon-sminq** [transloadit/java-sdk#21]
We tried the new SDK and the uploadProgress does not return bytes in batches, but directly returns 100%.
Which does not help to display upload progress.

**Comment by ifedapoolarewaju** [comment]
@sheldon-sminq this is because by default the upload chunk size is set to 2MB. So with a file size <= 2MB, it would all get uploaded at once with no progress update in between. However, for files larger than 2MB, you would get an upload progress for every 2MB chunk uploaded. Does this make sense to you?

**Comment by ifedapoolarewaju** [comment]
> Is this setting available per account

as of now, no, but it can be easily added.

**Comment by ifedapoolarewaju** [comment]
@sheldon-sminq this issue is now fixed and released [here](https://github.com/transloadit/java-sdk/releases/tag/v0.1.1). You can now do `assembly.setUploadChunkSize(1024*500)` to set the upload intervals at which the upload progress should be propagated.
