### ISSUE TITLE
Modernize Gradle build instructions

### ISSUE THREAD

**Issue by Acconut** [transloadit/java-sdk#39]
In build.gradle:
- address deprecation notices from Intellij
- update dependencies

In examples:
- reference latest Java SDK version and not hardcode an old one.

**Comment by cdr-chakotay** [comment]
As I am currently working on that, two questions are remaining open, wich should be discussed.

- First of all Gradle warns about the source- and traget compatibility of Java 1.6. Maybe we should consider dropping 1.6 in favor of 1.8. In the light of switching to Github Actions this would make sense because Github Actions is only backwards compatible to Java 8.

- Second, maybe we should consider upgrading Gradle from 5.4.1 to 6.8.x to be more up-to-date. 
Would also fix a conflict with newer JDK versions.

**Comment by Acconut** [comment]
Yes, let's do both! It should be fine since Java 6 is quite old and Java 8 is a LTS release, so we should still keep it. If a customer runs into a problem, we can find a solution.
